name: Build & Deploy
on:
  push: 
    branches: 
      [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy to digitalocean
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          
          script: |
            mkdir cba
            cd cba
            git clone git@github.com:CurrentBestAnswers/current-best-answers.git
            echo 'Deployment successful'
